module Booker
  module Models
    class AppointmentTreatment < Model
      attr_accessor 'AppointmentID',
        'DynamicPrice',
        'EndDateTime',
        'ID',
        'StartDateTime',
        'ChildID',
        'ChildName',
        'AllowChangeStartTime',
        'DynamicPriceID',
        'Employee',
        'Employee2FullName',
        'Employee2ID',
        'EmployeeFirstName',
        'EmployeeFullName',
        'EmployeeID',
        'EmployeeLastName',
        'EmployeeRecoveryDuration',
        'EmployeeTypeID',
        'EmployeeWasRequested',
        'FinishStartDateTime',
        'FinishTimeAppliedToEmployee',
        'FinishTimeAppliedToRoom',
        'FinishTimeDuration',
        'FinishTimeOriginalDuration',
        'ProcessingStartDateTime',
        'ProcessingTimeAppliedToRoom',
        'ProcessingTimeAppliedToEmployee',
        'ProcessingTimeDuration',
        'ProcessingTimeOriginalDuration',
        'RequiresProcessingTime',
        'Room',
        'RoomID',
        'RoomName',
        'RoomRecoveryDuration',
        'StartTimeDuration',
        'StartTimeOriginalDuration',
        'TagPrice',
        'Treatment',
        'TreatmentDuration',
        'TreatmentID',
        'TreatmentIsForCouples',
        'TreatmentName',
        'ClassInstanceID',
        'IsDurationOverridden'
    end
  end
end

