require 'spec_helper'

describe Booker::V4::Models::Appointment do
  it { is_expected.to be_a Booker::V4::Models::Model }

  it 'has the correct attributes' do
    ['BookingNumber',
      'Confirmable',
      'EndDateTime',
      'FinalTotal',
      'ID',
      'IsCancelled',
      'IsNoShow',
      'LocationID',
      'StartDateTime',
      'Status',
      'CanTakePayment',
      'DateCreated',
      'BelongsToEnrollment',
      'Address',
      'AddressID',
      'AllowAutoPay',
      'AppointmentTreatments',
      'BelongsToGroup',
      'BelongsToGroupAndGroupOrder',
      'BelongsToOrder',
      'CanCancel',
      'CanCheckin',
      'CanHaveCustomer2',
      'CanRevertNoShow',
      'CanUndoCheckin',
      'CancellationID',
      'Customer',
      'Customer2',
      'Customer2ID',
      'CustomerID',
      'CustomerLastName',
      'CustomerMobilePhone',
      'CustomerWorkPhone',
      'DateBooked',
      'DateNoShow',
      'Employee',
      'EmployeeFirstName',
      'EmployeeLastName',
      'GroupID',
      'GroupName',
      'GroupNumber',
      'GroupTypeID',
      'IsCancelledOrNoShow',
      'IsCheckedInInService',
      'IsPartOfClassPackageBooking',
      'IsPreBookedAtPastCheckout',
      'IsRecurring',
      'IsWebBooking',
      'Notes',
      'OrderID',
      'OrderStatusID',
      'PackageID',
      'PaymentID',
      'PaymentItemID',
      'PrimaryAppointmentTreatmentID',
      'RecurrenceID',
      'Room',
      'Source',
      'Treatment',
      'TreatmentName',
      'Type',
      'IsHeld',
      'HoldForMinutes',
      'HeldSince',
      'IsServiceComplete',
      'IsCheckout',
      'DateCheckIn',
      'IsFromWaitList',
      'IsFromClassWaitList',
      'CustomerRecordTypeID',
      'CustomerParentID'].each do |attr|
      expect(subject).to respond_to(attr)
      expect(subject).to respond_to("#{attr}=")
    end
  end
end
