module Booker
  module V4
    module Models
      class Special < Model
        attr_accessor 'ID',
                      'LocationID',
                      'Name',
                      'Description',
                      'CouponCode',
                      'Type',
                      'ShortUrl',
                      'ApplicableStartDate',
                      'ApplicableEndDate',
                      'BookingDateType',
                      'BookingStartDate',
                      'BookingEndDate',
                      'BookingEarlyBirdUnit',
                      'BookingEarlyBirdUnitType',
                      'BookingLastMinuteUnit',
                      'BookingLastMinuteUnitType',
                      'MaxRedemptions',
                      'TimeOfDayStart',
                      'TimeOfDayEnd',
                      'HasTreatment',
                      'WeekDays',
                      'UsePriceRanges',
                      'PriceRanges',
                      'DiscountType',
                      'AdjustmentType',
                      'DiscountAmount',
                      'CanCustomerDirectBook',
                      'HideOnInvoicesAndReceipts',
                      'PhotoUrl',
                      'UsedRedemptions',
                      'AvailableRedemptions',
                      'SpecialItems',
                      'HasFreeItems',
                      'FreeItems',
                      'PriceRangeScope',
                      'ApplicationItemIDs',
                      'IsExclusiveWithAll',
                      'IsExclusiveWithAny',
                      'Exclusions',
                      'CombinationRules',
                      'ApplicableStartDateOffset',
                      'ApplicableEndDateOffset',
                      'BookingStartDateOffset',
                      'BookingEndDateOffset',
                      'TimeOfDayStartOffset',
                      'TimeOfDayEndOffset'
      end
    end
  end
end
